export const AUTH_START = "AUTH_START";

export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_LOGOUT= "AUTH_LOGOUT";


//WISHLIST
export const WISHLIST_FETCH_START = "WISHLIST_FETCH_START";

export const FETCH_WISHLIST = "FETCH_WISHLIST";

export const WISHLIST_FETCH_SUCCESS = "WISHLIST_FETCH_SUCCESS";

export const EMPTY_WISHLIST = "EMPTY_WISHLIST";


//CART
export const ADD_TO_CART="ADD_TO_CART";

export const CLEAR_CART="CLEAR_CART";

export const INCREASE_QUANTITY="INCREASE_QUANTITY";

export const DECREASE_QUANTITY="DECREASE_QUANTITY";

export const UPDATE_TOTAL="UPDATE_TOTAL";

export const REMOVE_FROM_CART ="REMOVE_FROM_CART";


// Order
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS';

export const ORDER_FETCH_START = 'ORDER_FETCH_START';

export const ORDER_FETCH_FAIL = 'ORDER_FETCH_FAIL';

export const EMPTY_ORDERS = 'EMPTY_ORDERS';

export const DELIVERED_FETCH_SUCCESS = 'DELIVERED_FETCH_SUCCESS';

export const DELIVERED_FETCH_FINISH ='DELIVERED_FETCH_FINISH';

//feedback
export const ADD_TO_FEEDBACK='ADD_TO_FEEDBACK';

export const FEEDBACK_FETCH_START = "FEEDBACK_FETCH_START";
